### ISSUE TITLE
doesnt support multiple CacheDir

### ISSUE THREAD

**Issue by ArielRosenfeld** [eworm-de/pacredir#3]
if 
CacheDir    = /mnt/scratch/var/cache/pacman/pkg/ /var/cache/pacman/pkg/
is set in pacman.conf it doesnt look in both locations for packages as its set in pacserve.service using default location only

**Comment by eworm-de** [comment]
The cache directory is served by `pacserve`, which is just a static http server `darkhttpd`. I do not think there is an easy way to make it handle several directories...

I will think about it - if you have any ideas please share.

**Comment by ArielRosenfeld** [comment]
a possible fix is to use overlayfs to merge the package directories as a read only mount

**Comment by eworm-de** [comment]
Sadly that does not work. With overlay filesystem all read only or lower layers are considered static, changing files there brings undefined behavior. See [Linux documentation on overlayfs](https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt), search for "Changes to underlying filesystems".

**Comment by eworm-de** [comment]
You could run nginx on port 7078 with a configuration that tries several paths:
[Nginx - Search for static content in multiple directories?](https://stackoverflow.com/questions/5555419/nginx-search-for-static-content-in-multiple-directories)
