### ISSUE TITLE
Support for multiple Manjaro branches

### ISSUE THREAD

**Issue by Bleuzen** [eworm-de/pacredir#5]
Hi, I'm using pacredir on Manjaro and like it so far.
But there is a problem: We have 3 branches on Manjaro: stable, testing and unstable.
I usually have one machine on testing and the rest on stable.

The problem with this is: when using pacredir and running
`pacman -Syyu`
on the machines on stable branch, they also get the updates from testing (because one machine is on testing in my network).

The solution I first think of (but maybe you know a better one):
Just don't sync the database through pacredir. Add an option to get the database always from a 'real' mirror.

**Comment by eworm-de** [comment]
For Arch Linux this works without issues. We have stable repositories `core`, `extra` and `community` with a database file for each (`core.db`, `extra.db` and `community.db`). The `testing` Repositories just have extra database files `testing.db` and `communinty-testing.db`. What ever files are provided by a number of clients - a client on stable repositories will never download one of the testing database files.
How exactly is that changed for Manjaro to break pacredir?

**Comment by eworm-de** [comment]
Just an idea on how to simply disable sharing of database files... Create a systemd service overlay config `/etc/systemd/system/pacserve.service.d/no-db.conf`:
```
[Service]
BindReadOnlyPaths=/var/cache/pacman/pkg:/run/pacserve/pkg
```

**Comment by Bleuzen** [comment]
On Manjaro this is a little different. There is no testing, community-testing,... repo.
The repos are always called: `core`, `extra`, `community` and `multilib` (on every branch).

The only things changing when switching branches in Manjaro are the urls in `/etc/pacman.d/mirrorlist`.
This is what this file looks like on stable:
```
## Country : France
Server = http://kibo.remi.lu/stable/$repo/$arch

## Country : Germany
Server = https://mirror.netzspielplatz.de/manjaro/packages/stable/$repo/$arch

... (more mirrors)

```

when setting the branch to testing, this file changes to:
```
## Country : France
Server = http://kibo.remi.lu/testing/$repo/$arch

## Country : Germany
Server = https://mirror.netzspielplatz.de/manjaro/packages/testing/$repo/$arch

... (more mirrors)

```

**Comment by eworm-de** [comment]
Ok, got it.

So does my config overwrite snippet help?

**Comment by Bleuzen** [comment]
No, this has no effect. I created the file with the content you wrote above on both machines and rebooted both. Still the stable machine is getting the testing updates after `pacman -Syyu`.

**Comment by eworm-de** [comment]
> No, this has no effect. I created the file with the content you wrote above on both machines and rebooted both. Still the stable machine is getting the testing updates after pacman -Syyu.

We have to clear the option before... So try this:
```
[Service]
BindReadOnlyPaths=
BindReadOnlyPaths=/var/cache/pacman/pkg:/run/pacserve/pkg
```
> Btw. I also had to create the directory /etc/systemd/system/pacserve.service.d/ myself. Is this correct, or should it pre exist?
> I'm using your package from the arch repo, but the pacserve.service.d dir was not there.

That's correct as we do not overwrite options for Arch. ;)

**Comment by Bleuzen** [comment]
Yes, this worked, thank you! :)

**Comment by Bleuzen** [comment]
Don't know if you want to do this, because this is an arch package, but:

An idea to further improve this may be to put something like this in the post install script of the pacredir package:
```
if [ "$(cat /etc/os-release | grep ID= | cut -d '=' -f 2)" == "manjaro" ]; then
    mkdir -p /etc/systemd/system/pacserve.service.d/
    echo "[Service]
BindReadOnlyPaths=
BindReadOnlyPaths=/var/cache/pacman/pkg:/run/pacserve/pkg" > /etc/systemd/system/pacserve.service.d/no-db.conf
fi
```

**Comment by eworm-de** [comment]
No, the Arch package will not have code for different distribution.
There is no Manjaro package for pacredir? I could think about handling this at build time.

**Comment by Bleuzen** [comment]
Manjaro uses about 95 % the packages from Arch. So if we install the pacredir package in Manjaro, it is just the Arch package.

I will ask in the Manjaro forum, if they want to maintain their own version of this package ...

**Comment by Bleuzen** [comment]
Forum post created.
Will see what they will reply...

https://forum.manjaro.org/t/manjaro-specific-build-of-pacredir/93054

**Comment by Ste74** [comment]
Hi there,
Manjaro team here.. I can rename your project into manjaro-pacredir and add the systemd service (workaround) at build time? At the moment i not checked if this pkg is Blacklisted in our repo ( i m at Smartphone now) if not i build with the same name in our overlay.. Do you think?

**Comment by Bleuzen** [comment]
You can build the package with the same name, since it doesn't make much sense to keep the Arch version in Manjaro repos.

**Comment by eworm-de** [comment]
Anybody wants to have a look at (and test) 37706ce06c15ea3af0de6c0f4685ce8fdc5218d4? Probably the cleanest we can get.

**Comment by eworm-de** [comment]
I released version 0.4.2... Please revert your workaround, install the update, then set `ignore db files = true` in configuration.

**Comment by Bleuzen** [comment]
@eworm-de Ok thanks, will give it a try soon.

@Ste74 Can we build our own version anyway? Because to just leave this option there, (and also pretty bad documentated at the moment) won't help.
Nobody will know that he has to enable it on Manjaro.
Also, Manjaro users are more used to 'it just works / don't have to change config files'.
So I would prefer it if you can build a Manjaro specifiy pacredir package with this new option set in config file by default.

**Comment by Bleuzen** [comment]
@eworm-de New version works fine here. I set this option to true and also get "Ignoring request for db file ..." in log. Nice, thank you!

**Comment by eworm-de** [comment]
Great, so have fun! ;)
