### ISSUE TITLE
Allow setting package directory

### ISSUE THREAD

**Issue by ArielRosenfeld** [eworm-de/pacredir#6]
Allow setting the package directory or get it from /etc/pacman.conf CacheDir setting

its currently hardcoded in pacserve and has no setting in /etc/pacredir.conf

**Comment by eworm-de** [comment]
You could do that with systemd configuration overwrites. Create a file `/etc/systemd/system/pacserve.service.d/paths.conf` with content:
```
[Service]
BindReadOnlyPaths=
BindReadOnlyPaths=/path/to/your/files:/run/pacserve/pkg /var/lib/pacman/sync:/run/pacserve/db
```
Alternativly run  you your own webserver on port 7078.
