### ISSUE TITLE
A mirror central cache

### ISSUE THREAD

**Issue by ArielRosenfeld** [eworm-de/pacredir#7]
Use a client that mirrors all requests so a mirror of all packages requested is copied into a central location so even if a client it offline like a pc or laptop going to sleep a copy of the package is available on a dedicated machine that doesn't sleep

also setting a non /var location for that cache would be nice

**Comment by eworm-de** [comment]
That's out of scope for this project.
Perhaps you should set up cron with rsync jobs...
