### ISSUE TITLE
Builds done on Manjaro do not work

### ISSUE THREAD

**Issue by Bleuzen** [eworm-de/pacredir#8]
Hi, Manjaro now has it's own package of pacredir (with a different default config, as discussed in https://github.com/eworm-de/pacredir/issues/5).

But everytime I install a package with pacman, I see this in pacredir logs:
```
Currently no servers are available to check for SOME-PACKAGE.pkg.tar.xz.
...
```
This happens for all packages, even if they exist on another computer in the same network.

The server side works. So I can browse to
http://my-server-ip:7078/pkg/SOME-PACKAGE.pkg.tar.xz
on my client and it starts downloading the package.

Only the client side doesn't work, it never finds the packages.

---------

Now I installed the pacredir package from the Archlinux repo on my client, and: It works!
I installed the pacredir package from the Manjaro repo again, and I only get `Currently no servers are available to check for...` messages again.

I compared the PKGBUILDs and there is no big difference which could cause this.
So I decided to build it myself and test.

I used the exact build files provided here:
https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/pacredir
and built it on my Manjaro system.
The result is the same as using the pacredir package from the Manjaro repos: `Currently no servers are available to check for...`
Installing the arch package again (should be built with same PKGBUILD), and it works again.

So it makes a difference if pacredir is built on a Arch or Manjaro system.

During build, this prints:
```
==> Entpacke Quellen...
  -> Entpacke pacredir-0.4.2.tar.xz mit bsdtar
==> Beginne build()...
cp config.def.h config.h
printf "#ifndef VERSION\n#define VERSION \"%s\"\n#endif\n" 0.4.2 > version.h
sed 's/%ARCH%/x86_64/;s/%ID%/manjaro/' avahi/pacserve.service.in > avahi/pacserve.service
markdown README.md > README.html
gcc pacredir.c -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c11 -O2 -fPIC -Wall -Werror -lpthread -lsystemd  -lcurl  -D_REENTRANT -lavahi-common -lavahi-client  -I/usr/include/p11-kit-1 -lmicrohttpd  -liniparser -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-z,now -Wl,-z,relro -pie -DREPRODUCIBLE=0 -DARCH=\"x86_64\" -DID=\"manjaro\" -o pacredir
==> Betrete fakeroot Umgebung...
==> Beginne package()...
```
Take a look at the line with sed. It replaces something with 'manjaro' in the avahi service. On arch I guess, it replaces it with 'arch'.
Also, same goes for gcc compile option DID=\"manjaro\".

So there really is a difference during build, and this makes pacredir not work anymore.

What to do?

**Comment by Bleuzen** [comment]
Ok, found it myself. We have to change `/etc/avahi/services/pacserve.service`.
From
```
  <service>
    <type>_pacserve_arch_x86_64._tcp</type>
    <port>7078</port>
  </service>
```

```
  <service>
    <type>_pacserve_manjaro_x86_64._tcp</type>
    <port>7078</port>
  </service>
```

Sorry for interrupting.

**Comment by eworm-de** [comment]
The build process take `ID` from `/etc/os-release`. So `arch` and `manjaro` builds will not see each other. You should be fine if all your systems run packages built on `manjaro` boxes.

**Comment by Bleuzen** [comment]
Yes, this took me some time to realize. Thanks for explanation.
It was not working because on one machine I still had the arch package installed and forgot it.
