### ISSUE TITLE
Honoring "protocol = IPv4" in config

### ISSUE THREAD

**Issue by Hydroxides** [eworm-de/pacredir#9]
I have used the default "IPv4" and found the pacserve systemd unit fails to start with the following error:-

pacserve: socket(): Address family not supported by protocol

I have ipv6 disabled via kernel parameter ("ipv6.disable=1") as it caused problems with other, unrelated software. When I checked the systemd unit I found a line which suggests ipv6 was always enabled, regardless of the configuration:-

ExecStart=/usr/bin/pacserve /run/pacserve/ --ipv6 --port 7078 --no-listing

Removing " --ipv6" allowed the unit to start correctly and serve files as it should.

**Comment by eworm-de** [comment]
From configuration file:

> Specify to use IPv4, IPv6 or both. This does *not* limit the protocol for
> requests but what discovered services from avahi are handled.

So this is expected behavior. Running a system without IPv6 support is pretty uncommon these days.

As a workaround you could create a systemd configuration overwrite. Drop a file `/etc/systemd/system/pacserve.service.d/no-ipv6.conf`with this content:

> [Service]
> ExecStart=
> ExecStart=/usr/bin/pacserve /run/pacserve/ --port 7078 --no-listing
